/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MapRouteImport } from './routes/map'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AddngoRouteImport } from './routes/addngo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as NgosNgoIdRouteImport } from './routes/ngos.$ngoId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AddngoRoute = AddngoRouteImport.update({
  id: '/addngo',
  path: '/addngo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const NgosNgoIdRoute = NgosNgoIdRouteImport.update({
  id: '/ngos/$ngoId',
  path: '/ngos/$ngoId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addngo': typeof AddngoRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/ngos/$ngoId': typeof NgosNgoIdRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addngo': typeof AddngoRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/ngos/$ngoId': typeof NgosNgoIdRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addngo': typeof AddngoRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/ngos/$ngoId': typeof NgosNgoIdRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addngo'
    | '/events'
    | '/map'
    | '/news'
    | '/courses/$courseId'
    | '/ngos/$ngoId'
    | '/courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addngo'
    | '/events'
    | '/map'
    | '/news'
    | '/courses/$courseId'
    | '/ngos/$ngoId'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/addngo'
    | '/events'
    | '/map'
    | '/news'
    | '/courses/$courseId'
    | '/ngos/$ngoId'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddngoRoute: typeof AddngoRoute
  EventsRoute: typeof EventsRoute
  MapRoute: typeof MapRoute
  NewsRoute: typeof NewsRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  NgosNgoIdRoute: typeof NgosNgoIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addngo': {
      id: '/addngo'
      path: '/addngo'
      fullPath: '/addngo'
      preLoaderRoute: typeof AddngoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngos/$ngoId': {
      id: '/ngos/$ngoId'
      path: '/ngos/$ngoId'
      fullPath: '/ngos/$ngoId'
      preLoaderRoute: typeof NgosNgoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddngoRoute: AddngoRoute,
  EventsRoute: EventsRoute,
  MapRoute: MapRoute,
  NewsRoute: NewsRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  NgosNgoIdRoute: NgosNgoIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
